# Generated by Django 2.1 on 2020-01-13 09:03

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img_ID', models.IntegerField(null=True)),
                ('Img_File', models.ImageField(upload_to='')),
                ('GV_Result', jsonfield.fields.JSONField(null=True)),
                ('GV_Text_Logo_Json', jsonfield.fields.JSONField(null=True)),
                ('GV_Text', models.TextField(help_text='The OCRed text', null=True)),
                ('Website', models.URLField(null=True)),
                ('Created_Time', models.DateTimeField(auto_now=True)),
                ('Match_URL', models.CharField(max_length=300, null=True)),
                ('Match_Number', models.IntegerField(null=True)),
                ('Last_Update_Time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ocr_gv_result',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img_ID', models.IntegerField()),
                ('Match_URL', models.CharField(max_length=300, null=True)),
                ('Match_Number', models.IntegerField(null=True)),
                ('Last_Update_Time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ocr_match_choice',
            },
        ),
    ]
